[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"
authors = ["Xiaoming Yang"]
# The title and description fields are primarily for displaying extension info in UI
title = "Hue Control"
description="This extension Control Philips Hue light from Omniverse. Lighting design in Omniverse could be synchronised to real lights in real time."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/XiaomingY/omni-hue-control"

# One of categories for UI.
category = "Lighting"

# Keywords for the extension
keywords = ["Lighting", "Hue"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/HueControlScene.PNG"
icon = "data/icon.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.ui.scene" = {  }
"omni.usd" = {  }

# Main python module this extension provides, it will be publicly available as "import AimingTool".
[[python.module]]
name = "HueControl"
